package org.example.telegramBot;

public interface BotConstants {
    //    String TOKEN="5755340585:AAGT4kUnlhilEH-kyxRcpgLENNhsxxfbLbQ";
    //    String USERNAME="http://t.me/online_market_b24bot";
    String TOKEN = "5689048784:AAFacnY02Vab53zGCXAssPXjSO_8vkYCVNQ";
    String USERNAME = "@valyutaKonvertirOnlinebot";
    String MAIN_MENU = "MAIN MENU\uD83E\uDDFE";
    String SHARE_CONTACT = "\uD83D\uDCDESHARE CONTACT\uD83D\uDCDE";
    String SHARE_LOCATION = "\uD83D\uDCCDSHARE LOCATION\uD83D\uDCCD";

    String BASKET = "BASKET\uD83D\uDED2";
    String ALL_CATEGORIES = "ALL CATEGORIES ⌚ \uD83D\uDCF1 \uD83D\uDCBB";
    String CATEGORIES = "CATEGORIES⬇";
    String PRODUCTS = "PRODUCTS⬇";
    String ADD_BASKET = "ADD TO BASKET\uD83D\uDED2";
    String SUCCESSFULLY_ADDED = "SUCCESSFULLY ADDED☑";
    int HEAD_VALUE_CATEGORIES = 0;
    int COUNT_ONE_LINE_BUTTONS = 3;
    String START = "/start";
    String BACK = "BACK\uD83D\uDD19";
    String WELCOME = "WELCOME TO OUR BOT";
    int COUNT_BUTTONS = 3;
    String BUY = "BUY\uD83D\uDCB5";
    String DELETE_FROM_BASKET = "DELETE FROM BASKET\uD83D\uDDD1";

    String CATEGORY_SITTING="CATEGORY SITTING";
    String PRODUCT_SITTING="PRODUCT SITTING";
    String ADD_CATEGORY="ADD CATEGORY";
    String SHOW_CATEGORY_LIST="SHOW CATEGORY LIST";
    String DELETE_CATEGORY="DELETE CATEGORY";
    String ADD_PRODUCT="ADD PRODUCT";
    String DELETE_PRODUCT="DELETE PRODUCT";
    String UPDATE_PRODUCT="UPDATE PRODUCT";
    String SHOW_PRODUCT_LIST="SHOW PRODUCT LIST";




    String NOTEBOOK = "NOTEBOOK\uD83D\uDCBB";
    String TELEPHONE = "TELEPHONE\uD83D\uDCF1";
    String TV = "TV\uD83D\uDCFA";
    String COMPUTER_ACCESSORY = "COMPUTER ACCESSORY⌨\uD83D\uDDB1";
    String TELEPHONE_ACCESSORY = "TELEPHONE ACCESSORY\uD83D\uDD0B\uD83D\uDCDE";
    String HOUSE_APPLIANCES = "HOUSE APPLIANCES";

}
